### ISSUE TITLE
Blocked iframe

### ISSUE THREAD

**Issue by josephjthomas** [jenkinsci/sidebar-link-plugin#28] opened 2021-11-21 16:08 UTC
This plugin uses an iframe, that is blocked on Chrome 96.0.4664.45, Firefox v94.0.1 and Edge based on my testing,
![](https://i.imgur.com/nMzRpDr.png)

**Comment by damianszczepanik** [comment] 2021-11-21 20:30
This is not the plugin problem but Jenkins configuration

**Comment by aikebah** [comment] 2022-01-12 22:05
@damianszczepanik Are you sure on that? Because it appears to me (ran into the same issue) be the icon image upload for the sidebar plugin

```
				<div class="tr form-group">
					<div class="setting-main help-sibling">
						<iframe src="https://github.com/jenkinsci/sidebar-link-plugin" frameborder="0" style="width:100%;height:4em;margin-top:2em">
							<a href="https://github.com/jenkinsci/sidebar-link-plugin" target="_blank">Upload image file...</a>
						</iframe>
						<span class="setting-no-help"></span>
					</div>
					<div class="validation-error-area tr">
						<div colspan="2"></div>
						<div></div>
						<div></div>
					</div>
					<div class="help-area tr">
						<div class="help">Loading...</div>
					</div>
				</div>
```

Which would make me suspect some kind of a variable-name conflict within this plugin for variable-name 'url' during rendering which makes jelly somehow use the url of this plugin's github location as the evaluated value of `${url}`

https://github.com/jenkinsci/sidebar-link-plugin/blob/87f7f30bd5e45934773d0a497cab610fc6fa7d8c/src/main/resources/hudson/plugins/sidebar_link/SidebarLinkPlugin/config.jelly#L8-L13

**Comment by damianszczepanik** [comment] 2022-01-23 18:13
I meant that this should be configured by CSP https://support.mozilla.org/en-US/kb/xframe-neterror-page

This is how it looks with Chrome 97
![obraz](https://user-images.githubusercontent.com/9612911/150692031-307dece3-2cbf-4894-b43e-8dc806322e9b.png)

**Comment by aikebah** [comment] 2022-01-23 22:39
@damianszczepanik It's Github that disallows embedding.... but ... as said... in my view the 'upload image' iframe should not try to load github `https://github.com/jenkinsci/sidebar-link-plugin` which it what gets rendered by Jelly, but try to load `${rootURL}/plugin/sidebar-link/startUpload` (as appears to be configured in the quoted jelly-snippet).

From what I could see that snippet is unchanged for quite a while, so either in Jelly's internal working, or in some metadata of this plugin something appears to have changed that makes Jelly ignore the `<j:set var="url" value="${rootURL}/plugin/sidebar-link/startUpload"/> ` and keep it at some pre-set URL representing the plugin's github project.

This is what renders in Firefox with no sidebar links configured yet
![Screenshot 2022-01-23 at 23 33 54](https://user-images.githubusercontent.com/2175611/150700818-837c23b6-d6c6-4c3f-88ae-a80b9e0e43e6.png)
.

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-09 15:33
I see this too. Perhaps the wrong value of `${url}` comes from pom.xml here:

<https://github.com/jenkinsci/sidebar-link-plugin/blob/63ef2a3a69edae7ee8d5d212e04b977c209c8aa7/pom.xml#L13>

In which case, this could be fixed by renaming the `url` variable to something that does not conflict with things defined in the POM.

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-09 15:42
In the Jenkins controller, `plugins/sidebar-link/WEB-INF/lib/sidebar-link.jar` contains a `hudson/plugins/sidebar_link/SidebarLinkPlugin/config.jelly` file with this content:

```XML
<?jelly escape-by-default='true'?>
<j:jelly xmlns:j="jelly:core" xmlns:st="jelly:stapler" xmlns:d="jelly:define" xmlns:l="/lib/layout" xmlns:t="/lib/hudson" xmlns:f="/lib/form" xmlns:sl="/hudson/plugins/sidebar_link">
  <f:section title="${%Additional Sidebar Links}">
    <f:entry title="${%Sidebar Links}"
             description="${%List of extra links for Jenkins main pages and view tabs}">
      <sl:links links="${it.links}"/>
    </f:entry>
    <f:entry>
      <j:set var="url" value="${rootURL}/plugin/sidebar-link/startUpload"/>
      <iframe src="https://github.com/jenkinsci/sidebar-link-plugin" frameborder="0" style="width:100%;height:4em;margin-top:2em">
        <a href="https://github.com/jenkinsci/sidebar-link-plugin" target="_blank">${%Upload image file...}</a>
      </iframe>
    </f:entry>
  </f:section>
</j:jelly>
```

That means the `${url}` is replaced with `https://github.com/jenkinsci/sidebar-link-plugin` during the plugin build process, so the generated HTML does not depend on what value is assigned to the `url` variable at run time.

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-09 15:56
Version 1.10 of the Sidebar Link plugin did not have this bug yet. Version 1.11.0 had this bug but the URL pointed to the Jenkins wiki in that version. I think the bug was caused by the [resource filtering](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html) that was [added to pom.xml](https://github.com/jenkinsci/sidebar-link-plugin/pull/12/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R109-R114) between 1.10 and 1.11.0.

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-09 16:03
I ran `git grep '\${[^%]' -- src/main/resources/` and did not find any references to properties that should be replaced at build time. So if we just disable the resource filtering in pom.xml, then that should fix the bug and not break anything else.

**Comment by damianszczepanik** [comment] 2022-02-10 21:03
Are you talking about https://github.com/jenkinsci/sidebar-link-plugin/blob/master/pom.xml#L148 ?

**Comment by aikebah** [comment] 2022-02-10 21:14
@damianszczepanik Yes, that filtering option makes the maven-resources-plugin during the build replace ${url} with the url as configured at https://github.com/jenkinsci/sidebar-link-plugin/blob/de1ab4a046e5ffe35d19f33da5790e2780375ece/pom.xml#L13 thereby hardcoding the gitlab URL in the jelly-script as packaged in the sidebar-plugin distribution artifact

https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-10 21:24
Yeah, except it's not a git**lab** URL 😜

**Comment by aikebah** [comment] 2022-02-11 18:18
> Yeah, except it's not a git**lab** URL 😜

A typo by too much switching between two git hosting services

**Comment by KalleOlaviNiemitalo** [comment] 2022-02-13 13:39
There's a prerelease `sidebar-linki.hpi` downloadable from <https://ci.jenkins.io/job/Plugins/job/sidebar-link-plugin/job/PR-36/> if anyone wants to try my fix.

**Comment by aikebah** [comment] 2022-02-17 08:41
> There's a prerelease `sidebar-link.hpi` downloadable from https://ci.jenkins.io/job/Plugins/job/sidebar-link-plugin/job/PR-36/ if anyone wants to try my fix.

Can confirm that it works for me

**Closed** 2022-02-17 09:08 UTC
